# version: '3.8'

services:
  db:
    image: postgres:15
    container_name: movie-booking-db
    environment:
      POSTGRES_DB: movie_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - movie-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: movie-booking-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/movie_booking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      JWT_SECRET: zdwVX8uU+Uzo5IbQ3Ewxh6XlQSRTl6wZ8v4MhAD7/WnNp5ckXVTaxPeUFCE3e0uWMRrcp3WlgVJiTHa85HdHiQ==
      JWT_EXPIRATION: 86400000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - movie-network

volumes:
  pgdata:

networks:
  movie-network:
    driver: bridge 